"""Integration test: drive FrameProcessor against a Unix-socket sink, no HW.

Compares the wire-protocol bytes against a golden frame to catch unintended
changes in the dither output, the resize filter, or the protocol header.
"""

from __future__ import annotations

import hashlib
import os
import socket
import struct
import threading
from pathlib import Path
from unittest.mock import MagicMock

import numpy as np

from frame_processor.dispatch import MAGIC, SocketSink
from frame_processor.processor import PANEL_HEIGHT, PANEL_WIDTH, FrameProcessor

GOLDEN_DIR = Path(__file__).parent.parent / "golden"


def _accept_one_frame(sock_path: str) -> bytes:
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    server.bind(sock_path)
    server.listen(1)
    conn, _ = server.accept()
    chunks = []
    while True:
        chunk = conn.recv(65536)
        if not chunk:
            break
        chunks.append(chunk)
    conn.close()
    server.close()
    return b"".join(chunks)


def test_socket_sink_protocol(tmp_path: Path) -> None:
    sock_path = str(tmp_path / "preview.sock")

    received: list[bytes] = []

    def server() -> None:
        received.append(_accept_one_frame(sock_path))

    t = threading.Thread(target=server)
    t.start()

    # Wait for bind by retrying connect.
    sink: SocketSink | None = None
    for _ in range(50):
        try:
            sink = SocketSink(sock_path)
            sink.send(b"\x00" * (PANEL_WIDTH // 8 * PANEL_HEIGHT), PANEL_WIDTH, PANEL_HEIGHT)
            sink.close()
            break
        except (FileNotFoundError, ConnectionRefusedError):
            import time

            time.sleep(0.05)
    assert sink is not None

    t.join(timeout=5)
    assert received, "server thread did not capture a frame"
    blob = received[0]
    assert blob[:4] == MAGIC
    width, height = struct.unpack("<II", blob[4:12])
    assert (width, height) == (PANEL_WIDTH, PANEL_HEIGHT)
    assert len(blob) - 12 == PANEL_WIDTH // 8 * PANEL_HEIGHT


def test_processor_against_golden(tmp_path: Path) -> None:
    """Render a deterministic input frame and verify the dither output is stable.

    The golden file is generated by running this test once with EINKY_UPDATE_GOLDEN=1
    after a deliberate change to the pipeline.
    """
    rng = np.random.default_rng(0xE1)
    fake_rgb = rng.integers(0, 256, size=(PANEL_HEIGHT, PANEL_WIDTH, 3), dtype=np.uint8)

    capture = MagicMock()
    capture.grab.return_value = fake_rgb
    sink = MagicMock()
    sink.send = MagicMock()

    proc = FrameProcessor(capture=capture, sink=sink, target_fps=1.0)
    packed = proc.process_one()

    assert len(packed) == PANEL_WIDTH // 8 * PANEL_HEIGHT
    digest = hashlib.sha256(packed).hexdigest()

    golden = GOLDEN_DIR / "random_seed_e1.sha256"
    if os.environ.get("EINKY_UPDATE_GOLDEN") == "1":
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden.write_text(digest + "\n")
        return

    if not golden.exists():
        # No golden yet — record the digest in tmp for first-time inspection.
        (tmp_path / "first_run_digest.txt").write_text(digest + "\n")
        import pytest

        pytest.skip(
            f"no golden file at {golden}; rerun with EINKY_UPDATE_GOLDEN=1 to record. "
            f"first-run digest: {digest}"
        )

    expected = golden.read_text().strip()
    assert digest == expected, (
        f"dither output drifted. expected {expected}, got {digest}. "
        "If intentional, regenerate with EINKY_UPDATE_GOLDEN=1."
    )
