// ESP32 dev-bridge constants shared with the runtime ([[button]].esp32 pins,
// ports, frame magic, panel geometry).
//
// AUTO-GENERATED by ../../scripts/gen_from_contract.py from
// meta/shared/hardware.toml. Do not edit by hand — change the contract and run
// `make gen` from runtime/. The CI contract-parity job fails on drift.
#pragma once

// Panel geometry ([panel]).
#define EINKY_PANEL_W 800
#define EINKY_PANEL_H 480
#define EINKY_FRAME_BYTES 48000

// Frame wire protocol ([protocol.frame]).
#define EINKY_FRAME_MAGIC "EINK"
#define EINKY_FRAME_PORT 5333

// Input wire protocol ([protocol.input]).
#define EINKY_INPUT_PORT 5334

// Refresh policy ([refresh]): force a full refresh every N frames.
#define EINKY_FULL_REFRESH_EVERY 30

// Buttons ([[button]].esp32 pins; active-low with INPUT_PULLUP, debounce_ms).
#define EINKY_DEBOUNCE_MS 30
#define BTN_UP_PIN 32
#define BTN_DOWN_PIN 33
#define BTN_LEFT_PIN 25
#define BTN_RIGHT_PIN 26
#define BTN_A_PIN 27
#define BTN_B_PIN 14
#define BTN_START_PIN 12
