"""Panel + wire-protocol constants shared across the frame pipeline.

AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
Do not edit by hand — change the contract and run ``make gen``. The CI
contract-parity job fails if this file drifts from the contract.
"""

from __future__ import annotations

# Panel geometry ([panel]).
PANEL_WIDTH = 800
PANEL_HEIGHT = 480
FRAME_BYTES = 48000

# Refresh policy ([refresh]).
FULL_REFRESH_EVERY = 30

# Frame wire protocol ([protocol.frame]).
MAGIC = b"EINK"
FRAME_TCP_PORT = 5333
PREVIEW_SOCKET = "/tmp/einky-preview.sock"

# Input wire protocol ([protocol.input]).
INPUT_TCP_PORT = 5334

# In-engine capture protocol ([protocol.engine_capture]).
EINK_SOCKET = "/tmp/renpy-eink.sock"
INPUT_SOCKET = "/tmp/renpy-input.sock"
