/* Panel geometry + SPI / control pins for the GDEM0397T81P driver.
 *
 * AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
 * Do not edit by hand — change the contract and run `make gen`. The CI
 * contract-parity job fails if this file drifts from the contract.
 */
#ifndef EINKY_SPI_CONTRACT_H
#define EINKY_SPI_CONTRACT_H

/* Panel geometry ([panel]). */
#define EINKY_PANEL_W 800
#define EINKY_PANEL_H 480
#define EINKY_FRAME_BYTES 48000

/* SPI display device + pins ([spi], Raspberry Pi BCM numbering). MOSI/SCLK/CS are
 * owned by the kernel spidev driver; DC/RST/BUSY are driven directly via libgpiod. */
#define EINKY_SPI_DEV "/dev/spidev0.0"
#define EINKY_PIN_MOSI 10
#define EINKY_PIN_SCLK 11
#define EINKY_PIN_CS 8
#define EINKY_PIN_DC 25
#define EINKY_PIN_RST 17
#define EINKY_PIN_BUSY 24

#endif /* EINKY_SPI_CONTRACT_H */
