#!/usr/bin/env python3
"""Render committed constants from the shared hardware contract.

``meta/shared/hardware.toml`` is the single source of truth for panel geometry,
the GPIO / pin maps, button bindings, and wire-protocol constants (see ADR 0008).
Nothing in this repo may hard-code those values; instead this script renders the
contract into the per-language constant files each part of the runtime consumes:

    src/input/keymap.py                BUTTON_MAP + DEBOUNCE_SECONDS  (BCM / keysym)
    src/spi_driver/contract.h          panel geometry + SPI / control pins  (C)
    src/frame_processor/constants.py   panel + wire-protocol constants  (Python)
    firmware/esp32/include/contract.h  ESP32 button pins + ports + magic  (C++)

These rendered files are committed so the packages stay importable/compilable on
their own; the ``contract-parity`` CI job (and ``tests/unit/test_contract_parity.py``)
re-render in memory and fail if a committed copy drifts from the contract — the
same spirit as the ``install-script-parity`` job.

Usage::

    python scripts/gen_from_contract.py            # regenerate every file in place
    python scripts/gen_from_contract.py --check    # verify they match; write nothing
    python scripts/gen_from_contract.py --contract PATH   # use a non-default contract
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections.abc import Callable
from pathlib import Path

RUNTIME_ROOT = Path(__file__).resolve().parents[1]
# The contract lives in the sibling ``meta`` repo (``einky/meta`` locally; checked
# out next to ``runtime`` in CI). ``RUNTIME_ROOT.parent`` is that shared parent.
DEFAULT_CONTRACT = RUNTIME_ROOT.parent / "meta" / "shared" / "hardware.toml"

Contract = dict[str, object]


def load_contract(path: Path) -> Contract:
    with path.open("rb") as fh:
        return tomllib.load(fh)


# ── helpers ──────────────────────────────────────────────────────────────────


def _pystr(value: str) -> str:
    """Render a Python double-quoted string literal (contract values are plain ASCII)."""
    return '"' + value + '"'


def _button_const(name: str) -> str:
    return f"BTN_{name.upper()}_PIN"


# ── renderers (each returns the full file body, newline-terminated) ───────────


def render_keymap_py(c: Contract) -> str:
    spi = c["spi"]
    buttons = c["button"]
    assert isinstance(spi, dict) and isinstance(buttons, list)

    rows = "\n".join(
        f"    ButtonBinding({_pystr(b['name'])}, gpio={b['bcm']}, key={_pystr(b['keysym'])}),"
        for b in buttons
    )
    debounce_seconds = spi["debounce_ms"] / 1000

    return f'''\
"""GPIO -> keypress map: BCM pin -> X keysym, for the 4-way D-pad + 3 buttons.

AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
Do not edit by hand — change the contract and run ``make gen``. The CI
contract-parity job fails if this file drifts from the contract.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ButtonBinding:
    name: str
    gpio: int  # BCM pin number
    key: str  # X keysym (xdotool name) or evdev keycode name


# Each button's `gpio` is its Raspberry Pi BCM pin; `key` is the keysym injected
# on the X stack (the in-engine path maps the same `name` to renpy_events).
BUTTON_MAP: tuple[ButtonBinding, ...] = (
{rows}
)

# gpiozero bounce_time: the suppression window after a transition (debounce_ms).
DEBOUNCE_SECONDS = {debounce_seconds!r}
'''


def render_frame_constants_py(c: Contract) -> str:
    panel = c["panel"]
    refresh = c["refresh"]
    protocol = c["protocol"]
    assert isinstance(panel, dict) and isinstance(refresh, dict) and isinstance(protocol, dict)
    frame = protocol["frame"]
    inp = protocol["input"]
    capture = protocol["engine_capture"]
    assert isinstance(frame, dict) and isinstance(inp, dict) and isinstance(capture, dict)

    magic = frame["magic"]
    assert isinstance(magic, str)

    return f'''\
"""Panel + wire-protocol constants shared across the frame pipeline.

AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
Do not edit by hand — change the contract and run ``make gen``. The CI
contract-parity job fails if this file drifts from the contract.
"""

from __future__ import annotations

# Panel geometry ([panel]).
PANEL_WIDTH = {panel["width"]}
PANEL_HEIGHT = {panel["height"]}
FRAME_BYTES = {panel["frame_bytes"]}

# Refresh policy ([refresh]).
FULL_REFRESH_EVERY = {refresh["full_refresh_every"]}

# Frame wire protocol ([protocol.frame]).
MAGIC = {("b" + _pystr(magic))}
FRAME_TCP_PORT = {frame["frame_tcp_port"]}
PREVIEW_SOCKET = {_pystr(frame["preview_socket"])}

# Input wire protocol ([protocol.input]).
INPUT_TCP_PORT = {inp["input_tcp_port"]}

# In-engine capture protocol ([protocol.engine_capture]).
EINK_SOCKET = {_pystr(capture["eink_socket"])}
INPUT_SOCKET = {_pystr(capture["input_socket"])}
'''


def render_spi_contract_h(c: Contract) -> str:
    panel = c["panel"]
    spi = c["spi"]
    assert isinstance(panel, dict) and isinstance(spi, dict)

    return f"""\
/* Panel geometry + SPI / control pins for the GDEM0397T81P driver.
 *
 * AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
 * Do not edit by hand — change the contract and run `make gen`. The CI
 * contract-parity job fails if this file drifts from the contract.
 */
#ifndef EINKY_SPI_CONTRACT_H
#define EINKY_SPI_CONTRACT_H

/* Panel geometry ([panel]). */
#define EINKY_PANEL_W {panel["width"]}
#define EINKY_PANEL_H {panel["height"]}
#define EINKY_FRAME_BYTES {panel["frame_bytes"]}

/* SPI display device + pins ([spi], Raspberry Pi BCM numbering). MOSI/SCLK/CS are
 * owned by the kernel spidev driver; DC/RST/BUSY are driven directly via libgpiod. */
#define EINKY_SPI_DEV {_pystr(spi["dev"])}
#define EINKY_PIN_MOSI {spi["mosi"]}
#define EINKY_PIN_SCLK {spi["sclk"]}
#define EINKY_PIN_CS {spi["cs"]}
#define EINKY_PIN_DC {spi["dc"]}
#define EINKY_PIN_RST {spi["rst"]}
#define EINKY_PIN_BUSY {spi["busy"]}

#endif /* EINKY_SPI_CONTRACT_H */
"""


def render_esp32_contract_h(c: Contract) -> str:
    panel = c["panel"]
    refresh = c["refresh"]
    spi = c["spi"]
    protocol = c["protocol"]
    assert isinstance(panel, dict) and isinstance(refresh, dict)
    assert isinstance(spi, dict) and isinstance(protocol, dict)
    frame = protocol["frame"]
    inp = protocol["input"]
    buttons = c["button"]
    assert isinstance(frame, dict) and isinstance(inp, dict) and isinstance(buttons, list)

    magic = frame["magic"]
    assert isinstance(magic, str)

    pin_lines = "\n".join(f"#define {_button_const(b['name'])} {b['esp32']}" for b in buttons)

    return f"""\
// ESP32 dev-bridge constants shared with the runtime ([[button]].esp32 pins,
// ports, frame magic, panel geometry).
//
// AUTO-GENERATED by ../../scripts/gen_from_contract.py from
// meta/shared/hardware.toml. Do not edit by hand — change the contract and run
// `make gen` from runtime/. The CI contract-parity job fails on drift.
#pragma once

// Panel geometry ([panel]).
#define EINKY_PANEL_W {panel["width"]}
#define EINKY_PANEL_H {panel["height"]}
#define EINKY_FRAME_BYTES {panel["frame_bytes"]}

// Frame wire protocol ([protocol.frame]).
#define EINKY_FRAME_MAGIC {_pystr(magic)}
#define EINKY_FRAME_PORT {frame["frame_tcp_port"]}

// Input wire protocol ([protocol.input]).
#define EINKY_INPUT_PORT {inp["input_tcp_port"]}

// Refresh policy ([refresh]): force a full refresh every N frames.
#define EINKY_FULL_REFRESH_EVERY {refresh["full_refresh_every"]}

// Buttons ([[button]].esp32 pins; active-low with INPUT_PULLUP, debounce_ms).
#define EINKY_DEBOUNCE_MS {spi["debounce_ms"]}
{pin_lines}
"""


# Committed target path (relative to the runtime root) -> its renderer.
TARGETS: dict[str, Callable[[Contract], str]] = {
    "src/input/keymap.py": render_keymap_py,
    "src/frame_processor/constants.py": render_frame_constants_py,
    "src/spi_driver/contract.h": render_spi_contract_h,
    "firmware/esp32/include/contract.h": render_esp32_contract_h,
}


def render_all(c: Contract) -> dict[Path, str]:
    return {RUNTIME_ROOT / rel: render(c) for rel, render in TARGETS.items()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed files match the contract; write nothing (exit 1 on drift)",
    )
    parser.add_argument(
        "--contract",
        type=Path,
        default=DEFAULT_CONTRACT,
        help=f"path to hardware.toml (default: {DEFAULT_CONTRACT})",
    )
    args = parser.parse_args(argv)

    if not args.contract.exists():
        parser.error(f"contract not found: {args.contract}")

    contract = load_contract(args.contract)
    rendered = render_all(contract)

    drifted: list[Path] = []
    for path, body in rendered.items():
        rel = path.relative_to(RUNTIME_ROOT)
        if args.check:
            current = path.read_text() if path.exists() else None
            if current != body:
                drifted.append(rel)
                print(f"DRIFT: {rel}", file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
            print(f"wrote {rel}")

    if args.check:
        if drifted:
            print(
                f"\n{len(drifted)} file(s) out of sync with {args.contract}. "
                "Run `make gen` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("contract parity OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
