"""GPIO -> keypress map: BCM pin -> X keysym, for the 4-way D-pad + 3 buttons.

AUTO-GENERATED by scripts/gen_from_contract.py from meta/shared/hardware.toml.
Do not edit by hand — change the contract and run ``make gen``. The CI
contract-parity job fails if this file drifts from the contract.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ButtonBinding:
    name: str
    gpio: int  # BCM pin number
    key: str  # X keysym (xdotool name) or evdev keycode name


# Each button's `gpio` is its Raspberry Pi BCM pin; `key` is the keysym injected
# on the X stack (the in-engine path maps the same `name` to renpy_events).
BUTTON_MAP: tuple[ButtonBinding, ...] = (
    ButtonBinding("up", gpio=5, key="Up"),
    ButtonBinding("down", gpio=6, key="Down"),
    ButtonBinding("left", gpio=13, key="Left"),
    ButtonBinding("right", gpio=19, key="Right"),
    ButtonBinding("a", gpio=16, key="space"),
    ButtonBinding("b", gpio=20, key="Escape"),
    ButtonBinding("start", gpio=21, key="Return"),
)

# gpiozero bounce_time: the suppression window after a transition (debounce_ms).
DEBOUNCE_SECONDS = 0.03
